"""Add reminder to forums table

Revision ID: 7b7243bea62b
Revises: 
Create Date: 2026-05-11 22:00:07.107178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7243bea62b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    # 1. Try to drop the index
    try:
        with bind.begin_nested():
            op.drop_index(op.f('forum_cleanup_forum_id_key'), table_name='forum_cleanup')
    except Exception as e:
        print(f"Skipping drop_index: {e}")

    # 2. Create the unique constraint
    try:
        with bind.begin_nested():
            op.create_unique_constraint('forum_cleanup_forum_id_key_unique', 'forum_cleanup', ['forum_id', 'key'])
    except Exception as e:
        print(f"Skipping create_unique_constraint: {e}")

    # 3. Try to drop the old foreign key
    try:
        with bind.begin_nested():
            op.drop_constraint(op.f('forum_cleanup_forum_id_fkey'), 'forum_cleanup', type_='foreignkey')
    except Exception as e:
        print(f"Skipping drop_constraint: {e}")

    # 4. Final permanent changes (no nested block needed unless you want these optional too)
    try:
        with bind.begin_nested():
            op.create_foreign_key(None, 'forum_cleanup', 'forums', ['forum_id'], ['id'], ondelete='CASCADE')
    except Exception as e:
        print(f"Skipping create_foreign_key: {e}")
    op.add_column('forums', sa.Column('reminder', sa.String(length=2000), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forums', 'reminder')
    op.drop_constraint(None, 'forum_cleanup', type_='foreignkey')
    op.create_foreign_key(op.f('forum_cleanup_forum_id_fkey'), 'forum_cleanup', 'forums', ['forum_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('forum_cleanup_forum_id_key_unique', 'forum_cleanup', type_='unique')
    op.create_index(op.f('forum_cleanup_forum_id_key'), 'forum_cleanup', ['forum_id', 'key'], unique=True)
    # ### end Alembic commands ###
