"""Add reminder to forums table

Revision ID: 7b7243bea62b
Revises: 
Create Date: 2026-05-11 22:00:07.107178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7243bea62b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('forum_cleanup_forum_id_key'), table_name='forum_cleanup')
    op.create_unique_constraint('forum_cleanup_forum_id_key_unique', 'forum_cleanup', ['forum_id', 'key'])
    op.drop_constraint(op.f('forum_cleanup_forum_id_fkey'), 'forum_cleanup', type_='foreignkey')
    op.create_foreign_key(None, 'forum_cleanup', 'forums', ['forum_id'], ['id'], ondelete='CASCADE')
    op.add_column('forums', sa.Column('reminder', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forums', 'reminder')
    op.drop_constraint(None, 'forum_cleanup', type_='foreignkey')
    op.create_foreign_key(op.f('forum_cleanup_forum_id_fkey'), 'forum_cleanup', 'forums', ['forum_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('forum_cleanup_forum_id_key_unique', 'forum_cleanup', type_='unique')
    op.create_index(op.f('forum_cleanup_forum_id_key'), 'forum_cleanup', ['forum_id', 'key'], unique=True)
    # ### end Alembic commands ###
