import discord
from discord.ui import Separator, TextDisplay


class AutomodLayout(discord.ui.LayoutView) :
	"""This is the 2.0 embed layout for onboarding messages."""

	def __init__(self, rule_type: str, reason: str, title: str, content: str) :
		super().__init__(timeout=None)

		container = discord.ui.Container(
			TextDisplay(f"## Automod violation: {rule_type}"),
			Separator(),
			TextDisplay(f"Thread Title:\n{title}"),
			Separator(),
			TextDisplay(f"Messsage Content:\n{content}"),
			Separator(),
			TextDisplay(f"Reason:\n{reason}"),
			Separator(),
			TextDisplay(
				f"\n-# This message was generated by the automod system, if you think this is a mistake please contact the staff team.")

		)
		self.add_item(container)

	custom_id = "automod_layout"
